### ISSUE TITLE
[Metaissue] Priority tag existing issues

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epidatr#49]
Something like:

- [ ] P0 tag critical issues that need to be taken care before we officially release this package
- [ ] P1 tag less critical issues
- [ ] P2 tag feature enhancements

**Comment by brookslogan** [comment]
Took a stab at this, although with the more generic priority levels/meanings used across the other tooling repos.  I also kept a `triage` tag on ones where I was most uncertain about the priority level, but all are a little uncertain and would benefit from a second pair of eyes and more actual package testing to identify common pain points and desired features.
