### ISSUE TITLE
Complete first testing&documentation pass for remaining endpoints

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epidatr#54]
We are merging #23 as-is.  There are a few infrequently-used endpoints that have some remaining TODOs from this first pass.  Quoting from the list there:

- [x] dengue_nowcast (need valid locations, but API is lacking) EDIT: done in #102
- [x] dengue_sensors (need valid locations and names, but API is lacking) EDIT: done in #102
- [x] ecdc_ili EDIT: done in #102
- [x] kcdc_ili (need valid region, but API is lacking) EDIT: done in #102
- [x] paho_dengue (bug prevents testing) EDIT: done in #102

**Comment by dshemetov** [comment]
fixed by #102
