### ISSUE TITLE
Release the package

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epidatr#90]
This is a discussion thread for requirements for releasing the package.

## What does releasing the package entail?

- converging on a stable interface
  - this means breaking changes can't be made easily (requires a long warning process)
  - documentation and vignettes should be clean, friendly, and polished
  - error messages should be clear, friendly and informative
- publicizing the package, refactoring old code to use this package
- onramp to CRAN publication (not necessarily, but probably eventually)

## Requirements documentation

See [this thread](https://github.com/cmu-delphi/epidatr/issues/13#issuecomment-1072859520) for a checklist of features from original documents.

- [The original PRD](https://docs.google.com/document/d/1yhrQz5mdFnU9WJypFmDnkGhUOMbLWIpIU3RXcYc444w/edit)
- [Client library feature list](https://docs.google.com/spreadsheets/d/190HH854Yij4kccnWmVDjjeaSihiQiIB0ar2o8BvNyk4/edit#gid=185106297)

## TODO
- [x] Close remaining P0 issues
  - [x] Finish adaptations to API keys
  - [x] Clean and polish package documentation
  - [x] Clean and polish vignettes
  - [x] #145
  - [x] #144
- [x] Check that remaining P1 issues do not break user interface
  - [x] #124 involves CI
  - [x] #119 is a messaging line-wrapping issue
  - [x] #112 is a consistency for an internal that's marked experimental
  - [x] #109 is a documentation change
  - [x] #98 is a package-level error for an API level error
  - [x] #92 is the same
  - [x] #53 is fixed
  - [x] #10 concerns an experimental feature we won't release
- [x] Another documentation polish
  - [x] Get Ryan's feedback
  - [x] Get Alex's feedback
  - [x] Get Kean Ming's feedback
- [x] Tasks after the review session on August 22nd, 2023.
  - [x] #152
  - [x] #151
  - [x] #29 
  - [x] #144 
  - [x] #147 
  - [x] #148
  - [x] #112 
  - [x] #55 
  - [x] #157 
- [ ] Final tasks
  - [x] #168 
  - [ ] Blog post
  - [x] Submit to CRAN 
    - [x] Talk to Alex about CRAN hoops to jump through: what else is needed or do we just email someone and upload?
    - [x] Read through [CRAN submission guidelines](https://cran.r-project.org/web/packages/policies.html)
    - [x] Choose maintainer (this needs to be specified in the DESCRIPTION)
  - [ ] Celebrate with a chocolate apple!

**Comment by willtownes** [comment]
I tried building the package on my local machine and got the following warning:

```
checking S3 generic/method consistency ... WARNING
as.data.frame:
  function(x, row.names, optional, ...)
as.data.frame.covidcast_data_signal_list:
  function(signals, ...)

as.data.frame:
  function(x, row.names, optional, ...)
as.data.frame.covidcast_data_source_list:
  function(sources, ...)
See section ‘Generic functions and methods’ in the ‘Writing R
Extensions’ manual.
```

All the tests passed and there were no other errors, warnings, or notes.

**Comment by dsweber2** [comment]
@capnrefsmmat caught that here https://github.com/cmu-delphi/epidatr/issues/147. Glad that's consistently the only thing though.

**Comment by dshemetov** [comment]
It's here! 🎆🎆🎆

https://cran.r-project.org/web/packages/epidatr/index.html
